version: '3'

services:
  api:
    image: node
    user: node
    command: yarn dev
    depends_on:
      - mongodb
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - bolsa-net

  mongodb:
    image: mongo:latest
    volumes:
      - ~/docker-volumes/bolsa/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - bolsa-net

  postgres:
    image: postgres:latest
    volumes:
      - ~/docker-volumes/bolsa/postgres:/var/lib/postgresql/data
      - ~/docker-volumes/bolsa/dbscripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bolsa-net
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password

networks:
  bolsa-net:
    driver: bridge

secrets:
  postgres_password:
    file: ./.postgres-pwd
