version: '3'

services:
  api:
    image: node:fermium-alpine
    command: yarn dev
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - rs_ws_env_nw

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - rs_ws_env_nw

networks:
  rs_ws_env_nw:
